# YAML

Name: ODM2CZOData
Site Title: ODM2Admin
Site Header: ODM2Admin

Map Config:
  lat: 0
  lon: 0
  zoom: 2
  MapBox:
    access_token: mapbox accessToken
  cluster_sites: False
  time_series_months: 3

Data Disclaimer:
  text: Add a link discribing where your data come from
  linktext: The name of my site
  link: http://mysiteswegpage.page/

Secret Key: random_secret_key_like_so_7472873649836
Root: C:/Users/leonmi/Google Drive/ODM2Djangoadmin

Database config:
  name: database name
  user: database user
  password: database password
  host: 127.0.0.1
  port: 5432

Administrator:
  - name: first last
    email: email@example.com


